name: Go CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build Docker image
        run: docker build -t malinatrash/blockchain .

      - name: Push Docker image to registry
        run: |
          docker login -u malinatrash -p ${{ secrets.DOCKER_TOKEN }}
          docker push malinatrash/blockchain

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            docker ps -q --filter "name=malinatrash/blockchain" | xargs -r docker rm -f
            docker pull malinatrash/blockchain
            docker run -d -p 8080:8080 malinatrash/blockchain

