name: Go CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build
        run: go build -v ./cmd/main.go

      - name: Install application dependencies
        run: go mod tidy

      - name: Install Go
        run: |
          sudo apt-get update && sudo apt-get install -y golang
          echo "::add-path::/usr/lib/go-1.18/bin" # Add Go binary directory to PATH

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ./blockchain
            git pull origin master || git clone https://github.com/malinatrash/blockchain .
            go run ./cmd
