name: Go CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Build Docker image
        run: docker build -t malinatrash/blockchain .

      - name: Push Docker image to registry
        run: |
          docker login -u malinatrash -p ${{ secrets.DOCKER_TOKEN }}
          docker push malinatrash/blockchain

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
            CONTAINERS=$(docker ps -aq)
            for CONTAINER in $CONTAINERS; do
              NAME=$(docker inspect --format='{{.Name}}' $CONTAINER | sed 's@/@@')
              if [ "$NAME" != "wg-easy" ]; then
               docker stop $CONTAINER
               docker rm -f $CONTAINER
              fi
            done
            docker pull malinatrash/blockchain
            docker run -d -p 8080:8080 --name blockchain_container malinatrash/blockchain
